---
- name: setting baseline branch variable
  set_fact:
      baseline_branch: "{{target_branch}}"
  when:
      - target_branch == "candlepin-2.0-HOTFIX" or target_branch == "candlepin-2.1-HOTFIX"

- include: checkout.yml

- include: deploy.yml
  when: deploy_candlepin

- include: liquibase.yml
  when: provision_db

- include: test.yml
  when: run_test
